---
- name: Our first play
  hosts: planetexpress
  gather_facts: yes # runs by default
  connection: ansible.builtin.ssh

  tasks:

    - name: Install httpd on CentOS machines
      ansible.builtin.dnf:
        name: httpd
        state: present
      become: yes # run as sudo
      when: ansible_distribution == "CentOS"

    - name: Install steam locomotive on Ubuntu machines
      ansible.builtin.apt:
        name: sl
        state: present
      become: yes # run as sudo
      when: ansible_distribution == "Ubuntu"
